### ISSUE TITLE
2D annotations in dlc_pw and fte_pw folders (Dropbox)

### ISSUE THREAD

**Issue by julianzille** [African-Robotics-Unit/AcinoNet#17]
Hi everyone. 

Thank you for your work, and for making your data and results freely available. 

I'm trying to understand the difference between the 2D annotations stored in the `dlc_pw` and `fte_pw` folders in your Dropbox repository: are the 2D annotations in the .csv files in `fte_pw` obtained by re-projecting the 3D poses to 2D, and are the annotations in the .pickle files in `dlc_pw` generated by the DeepLabCut model which are used as GT (to compare with the re-projected 2D annotations)?

Thanks in advance :)

**Comment by MMathisLab** [comment]
hey @julianzille great you're using it! 

The 2D data is per-camera data, not reprojected actually 
dlc - means "raw" dlc output, 
- "fte" is the full trajectory opt. corrected data (best)

let me know if not clear

**Comment by julianzille** [comment]
Hi @MMathisLab - thank you. 

To understand correctly, is fte used to generate the most accurate 2D _and_ 3D annotations?

**Comment by MMathisLab** [comment]
correct!
