### ISSUE TITLE
Hand-checked 3D GT annotations

### ISSUE THREAD

**Issue by julianzille** [African-Robotics-Unit/AcinoNet#18]
Hi everyone.

The following paragraph is extracted from your paper: "We used this tool to estimate the amount of human corrections needed to be “perfect” (most needed no corrections, and minor corrections were under 10 pixels, checked on n=600 frames) and the largest adjustments were typically in the extremities, such as the tail and ankles. The proportion of large outliers where the adjustment was over 100 mm in magnitude was only 0.71%".

Are these 600 frames and their corrected annotations are available anywhere? Alternatively, are any hand-checked 3D GT frames/annotations available anywhere? Thanks in advance!

**Comment by MMathisLab** [comment]
Yes, the data is all available here: https://www.dropbox.com/sh/mto9ilgnopeixyp/AABSelc43yid-yenPVbeU9Ioa?dl=0

**Comment by julianzille** [comment]
@MMathisLab thank you. I apologise, my initial question was a bit vague...

If I'm correct, the hand-checked annotations are in `data/labeled_data/` and correspond to projections made from 3D FTE annotations to camera space (ie. they are 2D). However, I am looking for the 3D annotations corresponding to these projected annotations (if they exist). If not, are there any GT 3D annotations available (besides those generated by FTE)?

**Comment by amirpatel** [comment]
hi @julianzille 

@DJoska says he didn't upload those but is busy looking for them.

Regards
Amir

**Comment by amirpatel** [comment]
hi @julianzille 

@DJoska says he didn't upload those but is busy looking for them.

Regards
Amir
